# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160619_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
